url: https://RATStheatre.github.io/Bhopal-materials
baseurl:

# Site settings
title: We All Live in Bhopal
email: deepu@renegadeartsandtheatre.com
description: "We All Live in Bhopal is a piece written by Sudhir Selvaraj for the Renegade Arts and Theatre Society about the Bhopal Gas Tragedy, also known as the Union Carbide Disaster. With it being 30 years since the events, the script is a way to engage audiences about this significant chapter in Indian history. These scenes invite us to explore topics such as environmental damage, the role of civil society and the issue of corporate responsibility through the medium of theatre."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Maliha Ibrahim
  gravatar: "http://www.gravatar.com/avatar/44e17af10b8b7d65e2aa493baa03e4b0"
  position: Stage and Production Coordinator
  social:
    - title: google-plus
      url: https://plus.google.com/u/0/112222800327559923605/
    - title: wordpress
      url: http://virtuoso89.blogspot.com/

- name: Sudhir Selvaraj
  gravatar: "http://www.gravatar.com/avatar/79527ca98cca35d78dd19e7f6d85190e"
  position: Writer and Production Coordinator
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/sudhir-selvaraj/34/a92/274
    - title: instagram
      url: https://instagram.com/sudselvaraj

- name: Tanisha Christo
  gravatar: "http://www.gravatar.com/avatar/283dd0c8d83982d2b5592572025382a2"
  position: Lead Designer and Photographer
  social:
    - title: behance
      url: http://issuu.com/tanisha.christo/
    - title: wordpress
      url: http://fudge-together.blogspot.com/

- name: Deepu Philip
  gravatar: "http://www.gravatar.com/avatar/8cbc07784f08f9dadc84b7f41d96f33a"
  position: "Light Design and Technical Lead"
  social:
    - title: google-plus
      url: https://plus.google.com/u/0/+DeepuTPhilip/
    - title: github
      url: https://github.com/deepu-tp/

- name: Joel Louzado
  gravatar: "http://www.gravatar.com/avatar/b9a761f782cbf731db06df91b849b33e"
  position: Lead Developer and Social Media Manager
  social:
    - title: twitter
      url: https://twitter.com/jlouzado/
    - title: github
      url: https://github.com/jLouzado/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/RenegadeATS
  - title: facebook
    url: https://www.facebook.com/rats.theatre
  - title: github
    url: https://github.com/RATStheatre/Bhopal-materials

# Postal address (add as many lines as necessary)
address:
  - line: "33, 1st Cross, Vivekanada Nagar"
  - line: "Bangalore, India - 560033"

# Build settings
markdown: kramdown
permalink: pretty